name: soundify
description: A powerful Flutter library for contextual audio and sensory feedback.
version: 0.1.0
homepage: https://github.com/Deep3way/soundify
repository: https://github.com/Deep3way/soundify
issue_tracker: https://github.com/Deep3way/soundify/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  sensors_plus: ^5.0.0
  flutter_tts: ^4.0.0
  haptic_feedback: ^0.5.1+1  # Downgraded to a stable version

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
  assets:
    - assets/swipe.mp3
    - assets/shake.mp3
    - assets/click.mp3
    - assets/success.mp3